### ISSUE TITLE
Pyjion caused restart of the shell on IDLE

### ISSUE THREAD

**Issue by oroppas** [tonybaloney/Pyjion#19] opened 2020-11-22 02:49 UTC
On Windows,

![image](https://user-images.githubusercontent.com/885380/99892476-91ffd800-2cb8-11eb-899e-db039e611971.png)

**Comment by tonybaloney** [comment] 2020-11-22 04:38
thanks for the report. I'll try and reproduce this and see where the issue is coming from

**Comment by tonybaloney** [comment] 2020-11-28 07:20
Think this is fixed in 0.0.5

**Comment by tonybaloney** [comment] 2020-11-28 22:14
Confirmed fixed on 0.0.5 
![idlelib](https://user-images.githubusercontent.com/1532417/100527076-389d2900-3223-11eb-829a-229c959604fa.PNG)

**Closed** 2020-11-28 22:14 UTC
Labels: bug

**Comment by oroppas** [comment] 2020-11-29 06:19
@tonybaloney Thank you. I can JIT compile my function on Windows!
