### ISSUE TITLE
Error multiplying str returned from chr() builtin

### ISSUE THREAD

**Issue by ptmcg** [tonybaloney/Pyjion#315] opened 2021-07-14 10:42 UTC
See below REPR fragment:
Using .NET 6.0 Runtime (v6.0.0-preview.5)

```
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyjion
>>> pyjion.enable()
True
>>> x = lambda: chr(32) * 100
>>> x()
-100
>>> pyjion.disable()
True
>>> x()
'                                                                                                    '
>>> pyjion.__version__
'1.0.0b5'
```

**Comment by tonybaloney** [comment] 2021-07-15 00:05
thanks for the report. I can see where the issue is. I got `ord` and `chr` mixed up

**Comment by tonybaloney** [comment] 2021-07-15 00:43
The fix will be released in the next version

**Closed** 2021-07-15 00:42 UTC
